### ISSUE TITLE
Mocking .json file that doesn't exist in test environment

### ISSUE THREAD

**Issue by embpdaniel** [theKashey/rewiremock#71]
Hi @theKashey I have a .json config file that holds private keys that I should not add to my repo. When I make a commit my build pipeline runs tests, but it throws an error because it doesn't find the .json config file.

My thought was I can just mock it. So I tried:

`rewiremock('../config.json').by('./mocks/config.json')`

However this doesn't work, and throws an error saying it can't find the config.json file. It looks like the real config.json file needs to be there in order for me to mock it.

Is there some way I can write a mock where this file doesn't need to actually exist? Thanks in advance

**Comment by theKashey** [comment]
The problem is simple - it tries to understand the `real` name of the file you are going to mock, and thus failing.
What I could propose:
1. Just create it, and override in the build. Just imagine that you are using TypeScript, for example, and you have to _declare_ the public interface, the _shape_ of your configuration prior use.
2. Disable plugin which is looking for a file
```js
import rewiremock, { addPlugin, removePlugin, plugins } from 'rewiremock';
removePlugin(plugins .node);  
//......
addPlugin(plugins .node);  
```
3. The third option is to allow RegExp as a mock name, and then you will be able to mock whatever you want.
4. Add something like `{virtual:true}` from `jest.mock` to explicitly allow unexisting files.

(the first one is the best one)

**Comment by embpdaniel** [comment]
Thank you @theKashey these helped me understand. What I ended up doing was something similar to #1. I created a mock file, and then I controlled the location of the file by an environment variable. So in production it would be a path to the real file, and in test environment it is set to the path for the mock file. Worked perfectly

**Comment by theKashey** [comment]
👍
