### ISSUE TITLE
Could not get webpack setup working. Requesting example repo

### ISSUE THREAD

**Issue by suil** [theKashey/rewiremock#81]
Can someone point out a repo that has a working tests using rewiremock in webpack setup?

struggle to follow readme for setting webpack.

**Comment by theKashey** [comment]
1. Setup webpack
```js
plugins: [
    new webpack.NamedModulesPlugin(),               // this would keep file names
    new webpack.HotModuleReplacementPlugin(), // this would provide something alike module system
    new (require("rewiremock/webpack/plugin"))() // and this is rewiremock plugin
]
```
2. Try to use as _statically-analizable_ code, as possible.
If a module is not bundled by webpack - it could not be replaced. Prefer [guided mocking](https://github.com/theKashey/rewiremock#guided-mocking) - it solves the majority of problems.

Or you might be more concrete on what is actually not working for you.

**Comment by suil** [comment]
thanks for reply. here is the example repo i have https://github.com/suil/rewiremock-test

it should print out 'test data' instead of 'good data'

please check it out what went wrong.

**Comment by theKashey** [comment]
> Error: ../tests/rewiremock-test/src/fetch.js is set toBeUsed, but was unused

Two things to fix:
1. Your mock
```js
rewiremock('./src/fetch')
            .withDefault(() => Promise.resolve('test data')) // it's a function
            .toBeUsed();    // always good to have
```

2. Your webpack config
Just __remove__ `externals: [nodeExternals()],`, or blacklist `rewiremock` somehow - it shall be executed _inside_ webpack to have access to webpack internals.

**Comment by suil** [comment]
it works now. thx so much for helping.

another question: why you say `rewiremock('../src/fetch')` what is directory the path starts? project root? can this be changed?

**Comment by theKashey** [comment]
This is quite a tricky moment. 
- `node` and `webpack` _endpoints_ are adding `relativeName` plugin, which allows you to include a file, relatively to your location.
- given a file name, and "parent" module it's trying to find the file.
- for `nodejs` it's a build in API call `Module._resolveFilename`
- for `webpack` it's an overloaded version which enumerates __all__ bundled files and tries to find the best matching one

That said - you may include something using a name, relative to a current file, or an absolute name.
Absolute name, in case of webpack, would start from your project root, ie - `./src/fetch`. 

That's a tricky and a bit unstable moment, that's why I recommend to use `require`(guided mocking) to handle name resolution by the system itself.
